---------------------------------------
--- ADDING PRODUCTS
---------------------------------------
-- Insérer des données dans la table t_product
INSERT INTO t_product (product_name, description, price) VALUES 
('Montre Connectée', 'Montre connectée avec suivi d''activité', 199.99),
('Bouteille Isotherme', 'Bouteille isotherme pour boissons chaudes et froides', 25.50),
('Écouteurs Sans Fil', 'Écouteurs Bluetooth avec réduction de bruit', 89.99),
('Tapis de Yoga', 'Tapis antidérapant pour le yoga et le fitness', 45.00),
('Sac à Dos de Voyage', 'Sac à dos léger et résistant pour les voyages', 59.99),
('Chaussures de Course', 'Chaussures légères pour la course à pied', 79.99),
('Câble de Charge', 'Câble de charge USB-C pour appareils électroniques', 15.00),
('Clé USB 32 Go', 'Clé USB rapide et compacte de 32 Go', 12.50),
('Station Météo', 'Station météo numérique avec prévisions', 150.00),
('Support de Téléphone', 'Support de téléphone pour voiture', 20.00),
('Enceinte Bluetooth', 'Enceinte portable Bluetooth avec son de qualité', 99.99),
('Tablette Android', 'Tablette Android avec écran HD', 249.99),
('Montre Sportive', 'Montre sportive avec chronomètre et GPS', 120.00),
('Mini Drone', 'Mini drone avec caméra HD', 150.00),
('Chargeur Solaire', 'Chargeur solaire pour appareils mobiles', 45.00),
('Souris Ergonomique', 'Souris ergonomique pour le confort', 30.00),
('Télémètre Laser', 'Télémètre laser pour mesurer avec précision', 75.00),
('Batterie Externe', 'Batterie externe de 10000 mAh', 35.00),
('Lampe LED', 'Lampe LED rechargeable avec variateur', 40.00),
('Filtre à Eau', 'Filtre à eau pour carafe', 25.00),
('Mug Isotherme', 'Mug isotherme en acier inoxydable', 18.00),
('Pèse Personnelle', 'Pèse personnelle numérique', 50.00),
('Appareil Photo Instantané', 'Appareil photo instantané avec films', 120.00),
('Robot Aspirateur', 'Robot aspirateur automatique avec capteurs', 299.99),
('Porte-Clefs Bluetooth', 'Porte-clés connecté pour retrouver vos clés', 15.00),
('Bracelet Connecté', 'Bracelet connecté pour suivi de santé', 99.00),
('Vélo Électrique', 'Vélo électrique pliable', 899.99),
('Banc de Musculation', 'Banc de musculation réglable', 199.00),
('Tondeuse à Gazon', 'Tondeuse à gazon électrique silencieuse', 350.00),
('Batterie de Cuisine', 'Batterie de cuisine antiadhésive', 120.00),
('Couteau de Cuisine', 'Couteau de chef en acier inoxydable', 45.00),
('Set de Pinceaux', 'Set de pinceaux pour la peinture', 25.00),
('Coffre de Rangement', 'Coffre de rangement en plastique', 60.00),
('Jeu de Société', 'Jeu de société amusant pour toute la famille', 30.00),
('Tente de Camping', 'Tente de camping facile à monter', 120.00),
('Table de Pique-Nique', 'Table de pique-nique pliante', 150.00),
('Sac de Sport', 'Sac de sport avec compartiments', 40.00),
('Ballon de Football', 'Ballon de football en cuir', 25.00),
('Trousse de Premiers Secours', 'Trousse de premiers secours complète', 35.00),
('Système de Sécurité', 'Système de sécurité pour maison', 499.00),
('Coussin de Voyage', 'Coussin de voyage ergonomique', 20.00),
('Brosse à Dents Électrique', 'Brosse à dents électrique rechargeable', 55.00),
('Ouvre-Bouteille', 'Ouvre-bouteille en acier inoxydable', 10.00),
('Porte-Monnaie', 'Porte-monnaie en cuir', 22.00),
('Gourde en Acier', 'Gourde isotherme en acier inoxydable', 35.00),
('Lampe de Poche', 'Lampe de poche LED rechargeable', 15.00),
('Système Audio', 'Système audio surround pour cinéma maison', 300.00),
('Glacière Portable', 'Glacière portable pour les pique-niques', 60.00),
('Horloge Murale', 'Horloge murale design moderne', 30.00),
('Brosse de Nettoyage', 'Brosse de nettoyage multi-usages', 12.00),
('Sac de Couchage', 'Sac de couchage léger et compact', 80.00),
('Tasse à Café', 'Tasse à café en céramique avec motif', 12.50),
('Bouteille de Vin', 'Bouteille de vin rouge 2018', 25.00),
('Montre Vintage', 'Montre vintage avec bracelet en cuir', 150.00);